### ISSUE TITLE
Добавить шаблонные стили для example

### ISSUE THREAD

**Issue by Borodin** [Tour-360/tour-player#64]

**Comment by BorodinDK** [comment]
Например?

**Comment by Borodin** [comment]
```css

/* Цвет информационных маркеров */
.marker.info{
	background-color: #ed1c24;
}

/* Цвет полосы загрузки
#loader {
	background: #ed1c24;
} */

```
